//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SGame/GameService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "game.grpc.pb.h"
#include "GameService_Private.generated.h"

class UGameService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::game::GameService::Stub> Stub;
};


UCLASS()
class UGameServiceGetServiceVersionLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UGameServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGameGetServiceVersionResponse& Response);
public:
	FGrpcContextHandle Handle;
	UGameService::FGetServiceVersionResponseLambda ResponseLambda;
};

