//Generated by TurboLink CodeGenerator, do not edit!
#include "GameMarshaling.h"

void GRPC_TO_TURBOLINK(const ::game::GetServiceVersionRequest* in, FGrpcGameGetServiceVersionRequest* out)
{
}

void TURBOLINK_TO_GRPC(const FGrpcGameGetServiceVersionRequest* in, ::game::GetServiceVersionRequest* out)
{
}

void GRPC_TO_TURBOLINK(const ::game::GetServiceVersionResponse* in, FGrpcGameGetServiceVersionResponse* out)
{
    out->Version=StringCast<TCHAR>((const UTF8CHAR*)(in->version().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcGameGetServiceVersionResponse* in, ::game::GetServiceVersionResponse* out)
{
    out->set_version((const char*)StringCast<UTF8CHAR>(*(in->Version)).Get());
}

