//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SGame/GameMessage.h"
#include "SGame/GameMarshaling.h"
class GrpcContext_GameService_GetServiceVersion : public GrpcContext_Ping_Pong<GameService_GetServiceVersion_ReaderWriter, ::game::GetServiceVersionResponse>
{
	friend class UGameServiceClient;
	typedef GrpcContext_Ping_Pong<GameService_GetServiceVersion_ReaderWriter, ::game::GetServiceVersionResponse> Super;

private:
	void Call(const FGrpcGameGetServiceVersionRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_GameService_GetServiceVersion(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

