//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SAuth/AuthClient.h"
#include "AuthService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UAuthService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	UAuthServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UAuthServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcAuthLoginResponse& Response)> FGuestLoginResponseLambda;
	void CallGuestLogin(const FGrpcAuthGuestLoginRequest& Request, FGuestLoginResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcAuthValidateUserTokenResponse& Response)> FValidateUserTokenResponseLambda;
	void CallValidateUserToken(const FGrpcAuthValidateUserTokenRequest& Request, FValidateUserTokenResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	class Private;
	Private* const d = nullptr;

public:
	UAuthService();
	virtual ~UAuthService();
};

