//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "AuthMessage.h"
#include "AuthNode.generated.h"

class UAuthService;
class UAuthServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallAuthServiceGuestLogin : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FAuthServiceGuestLoginDelegate, const FGrpcResult&, GrpcResult, const FGrpcAuthLoginResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|AuthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call AuthService GuestLogin",
		AdvancedDisplay = 2))
	static UCallAuthServiceGuestLogin* GuestLogin(UObject* WorldContextObject, const FGrpcAuthGuestLoginRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FAuthServiceGuestLoginDelegate OnGuestLoginResponse;

	UPROPERTY(BlueprintAssignable)
	FAuthServiceGuestLoginDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UAuthService* AuthService;
	
	UPROPERTY()
	UAuthServiceClient* AuthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcAuthGuestLoginRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcAuthLoginResponse& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallAuthServiceValidateUserToken : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FAuthServiceValidateUserTokenDelegate, const FGrpcResult&, GrpcResult, const FGrpcAuthValidateUserTokenResponse&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|AuthService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call AuthService ValidateUserToken",
		AdvancedDisplay = 2))
	static UCallAuthServiceValidateUserToken* ValidateUserToken(UObject* WorldContextObject, const FGrpcAuthValidateUserTokenRequest& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FAuthServiceValidateUserTokenDelegate OnValidateUserTokenResponse;

	UPROPERTY(BlueprintAssignable)
	FAuthServiceValidateUserTokenDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UAuthService* AuthService;
	
	UPROPERTY()
	UAuthServiceClient* AuthServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcAuthValidateUserTokenRequest Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcAuthValidateUserTokenResponse& Response);

	void Shutdown();
};
