//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "AuthMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Auth.GuestLoginRequest"))
struct FGrpcAuthGuestLoginRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.LoginResponse"))
struct FGrpcAuthLoginResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Token = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.ValidateUserTokenRequest"))
struct FGrpcAuthValidateUserTokenRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Token = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.ValidateUserTokenResponse"))
struct FGrpcAuthValidateUserTokenResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool IsValid = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserName = "";
};
