//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SAuth/AuthMessage.h"
#include "AuthClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnAuthServiceGuestLoginResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcAuthResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnAuthServiceRegisterGameServerResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcAuthResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UAuthServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnAuthServiceGuestLoginResponse OnGuestLoginResponse;

	UPROPERTY(BlueprintAssignable)
	FOnAuthServiceRegisterGameServerResponse OnRegisterGameServerResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGuestLogin();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GuestLogin(FGrpcContextHandle Handle, const FGrpcAuthGuestLoginRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitRegisterGameServer();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void RegisterGameServer(FGrpcContextHandle Handle, const FGrpcAuthRegisterGameServerRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

