//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "AuthMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Auth.GuestLoginRequest"))
struct FGrpcAuthGuestLoginRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.RegisterGameServerRequest"))
struct FGrpcAuthRegisterGameServerRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString ServerName = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Auth.Response"))
struct FGrpcAuthResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Token = "";
};
