#pragma once
#include "NativeGameplayTags.h"

namespace SMTags
{
	namespace Ability
	{
		namespace Activation
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hold);
		}

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Caught);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Holded);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smashed);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CaughtExit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HoldedExit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CaughtExitOnStunEnd);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HoldedExitOnStunEnd);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immune);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CatchBuff);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakIndicator);
	}

	namespace AttributeSet
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHP);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HP);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveSpeed);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxStamina);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxSkillGauge);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillGauge);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Heal);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
	}

	namespace Character
	{
		namespace Cooldown
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hold);
		}

		namespace State
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincible);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnlimitStamina);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlashActivation);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hold);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Caught);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Holded);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neutralize);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smashing);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smashed);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreak);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreaked);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Uncatchable);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unholdable);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immune);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Charge);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImpactArrow);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowBullet);
		}
	}

	namespace Data
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Duration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown);
	}

	namespace Item
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeChanger);
	}

	namespace Event
	{
		namespace AnimNotify
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hold);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChargeEndEntry);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(PianoNoiseBreakShoot);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowBulletShoot);

			namespace ElectricGuitar
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakFlash);
			}

			namespace Attack
			{
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackStart);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(CanInput);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(CanProceedNextAction);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftSlashNext);
				UE_DECLARE_GAMEPLAY_TAG_EXTERN(RightSlashNext);
			}
		}

		namespace Character
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuzzerBeaterSmashEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuzzerBeaterEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CaughtExitEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neutralize);
		}

		namespace Tile
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(TileTrigger);
		}
	}

	namespace GameplayCue
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayNiagara);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileLaunch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileHit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileWallHit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hold);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CatchHit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neutralize);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ApplyHeal);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImmuneEnd);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImmuneMaterialApply_ElectricGuitar);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImmuneMaterialReset);

		namespace Common
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immune);
		}

		namespace Piano
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Archery);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArcheryProjectileCharge1);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArcheryProjectileCharge2);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArcheryHitCharge1);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArcheryHitCharge2);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImpactArrow);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImpactArrowExplosion);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImpactArrowHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreak);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakBurst);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakBurstHit);
		}

		namespace ElectricGuitar
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shoot);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShootProjectile);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShootHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowBullet);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowBulletProjectile);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowBulletHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlowBulletDebuff);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakFlash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakBurst);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakBurstHit);
		}

		namespace Bass
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SlashHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Charge);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChargeHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakBurst);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseBreakBurstHit);
		}

		namespace SpecialAction
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashSuccessWithCharacter);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashSplashHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashSuccessWithHealItem);
		}

		namespace JumpPad
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(UseJumpPad);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Land);
		}
	}
}
