#pragma once
#include "NativeGameplayTags.h"

namespace SMTags
{
	namespace Ability
	{
		namespace Activation
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
		}

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Caught);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smashed);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CaughtExit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CaughtExitOnStunEnd);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immune);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CatchBuff);
	}

	namespace AttributeSet::Character::Init
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveSpeed);
	}

	namespace Character::State
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Caught);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smashing);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smashed);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Uncatchable);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Immune);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
	}

	namespace Data
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Duration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveSpeed);
	}

	namespace Item
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeChanger);
	}

	namespace Event
	{
		namespace AnimNotify
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashEnd);
		}

		namespace Character
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuzzerBeaterSmashEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(CaughtExitEnd);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		}

		namespace Tile
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(TileTrigger);
		}
	}

	namespace GameplayCue
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayNiagara);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileLaunch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileLaunch_Sound);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileHit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProjectileWallHit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Catch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CatchHit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stun);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StunStart_Sound);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StunEnd_Sound);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ApplyHeal);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImmuneEnd);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImmuneMaterialApply_ElectricGuitar);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ImmuneMaterialReset);

		namespace SpecialAction
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Smash);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashSuccessWithCharacter);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashSplashHit);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashSuccessWithHealItem);
		}
		
		namespace JumpPad
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(UseJumpPad);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Land);
		}
	}
}
