//Generated by TurboLink CodeGenerator, do not edit!
#include "GreetMarshaling.h"

void GRPC_TO_TURBOLINK(const ::greet::HelloRequest* in, FGrpcGreetHelloRequest* out)
{
    out->Name=StringCast<TCHAR>((const UTF8CHAR*)(in->name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcGreetHelloRequest* in, ::greet::HelloRequest* out)
{
    out->set_name((const char*)StringCast<UTF8CHAR>(*(in->Name)).Get());
}

void GRPC_TO_TURBOLINK(const ::greet::HelloResponse* in, FGrpcGreetHelloResponse* out)
{
    out->Message=StringCast<TCHAR>((const UTF8CHAR*)(in->message().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcGreetHelloResponse* in, ::greet::HelloResponse* out)
{
    out->set_message((const char*)StringCast<UTF8CHAR>(*(in->Message)).Get());
}

