//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SGreet/GreetMessage.h"
#include "SGreet/GreetMarshaling.h"
class GrpcContext_GreeterService_SayHello : public GrpcContext_Ping_Pong<GreeterService_SayHello_ReaderWriter, ::greet::HelloResponse>
{
	friend class UGreeterServiceClient;
	typedef GrpcContext_Ping_Pong<GreeterService_SayHello_ReaderWriter, ::greet::HelloResponse> Super;

private:
	void Call(const FGrpcGreetHelloRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_GreeterService_SayHello(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

