//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SGreet/GreetService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "greet.grpc.pb.h"
#include "GreetService_Private.generated.h"

class UGreeterService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::greet::GreeterService::Stub> Stub;
};


UCLASS()
class UGreeterServiceSayHelloLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UGreeterServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGreetHelloResponse& Response);
public:
	FGrpcContextHandle Handle;
	UGreeterService::FSayHelloResponseLambda ResponseLambda;
};

