//Generated by TurboLink CodeGenerator, do not edit!
#include "SGoogleProtobuf/TimestampMessage.h"
#include "SGoogleProtobuf/TimestampMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcGoogleProtobufTimestamp, ::google::protobuf::Timestamp)

