//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SGoogleProtobuf/TimestampMessage.h"
#include "TurboLinkGrpcContext.h"
#include "google/protobuf/timestamp.pb.h"

void GRPC_TO_TURBOLINK(const ::google::protobuf::Timestamp* in, FGrpcGoogleProtobufTimestamp* out);
void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufTimestamp* in, ::google::protobuf::Timestamp* out);

