//Generated by TurboLink CodeGenerator, do not edit!
#include "SLobby/LobbyMessage.h"
#include "SLobby/LobbyMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcLobbyRoomConnectionInfo, ::lobby::RoomConnectionInfo)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyRoomConfig, ::lobby::RoomConfig)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyRoom, ::lobby::Room)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyCreateRoomRequest, ::lobby::CreateRoomRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyCreateRoomResponse, ::lobby::CreateRoomResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyJoinRoomRequest, ::lobby::JoinRoomRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyJoinRoomResponse, ::lobby::JoinRoomResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyGetRoomListRequest, ::lobby::GetRoomListRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyGetRoomListResponse, ::lobby::GetRoomListResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyUpdateRoomStateRequest, ::lobby::UpdateRoomStateRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyUpdateRoomStateResponse, ::lobby::UpdateRoomStateResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyUpdateRoomConfigRequest, ::lobby::UpdateRoomConfigRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyUpdateRoomConfigResponse, ::lobby::UpdateRoomConfigResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyChangeRoomPasswordRequest, ::lobby::ChangeRoomPasswordRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyChangeRoomPasswordResponse, ::lobby::ChangeRoomPasswordResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyChangeRoomOwnerRequest, ::lobby::ChangeRoomOwnerRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyChangeRoomOwnerResponse, ::lobby::ChangeRoomOwnerResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyDeleteRoomRequest, ::lobby::DeleteRoomRequest)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyDeleteRoomResponse, ::lobby::DeleteRoomResponse)
DEFINE_JSON_FUNCTIONS(FGrpcLobbyListenRoomUpdatesRequest, ::lobby::ListenRoomUpdatesRequest)

FGrpcLobbyJoinRoomRequestId UGrpcLobbyJoinRoomRequestIdHelperLibrary::MakeId(EGrpcLobbyJoinRoomRequestId IdCase, 
    FString RoomId, FString ShortRoomId 
)
{
    FGrpcLobbyJoinRoomRequestId Id;
    Id.IdCase = IdCase;
    Id.RoomId = RoomId;
    Id.ShortRoomId = ShortRoomId;

    return Id;
}

void UGrpcLobbyJoinRoomRequestIdHelperLibrary::BreakId(const FGrpcLobbyJoinRoomRequestId& Id, EGrpcLobbyJoinRoomRequestId& IdCase, 
    FString& RoomId, FString& ShortRoomId 
)
{
    IdCase = Id.IdCase;
    RoomId = Id.RoomId;
    ShortRoomId = Id.ShortRoomId;
}

