//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SLobby/LobbyMessage.h"
#include "TurboLinkGrpcContext.h"
#include "lobby.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::lobby::RoomInfo* in, FGrpcLobbyRoomInfo* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyRoomInfo* in, ::lobby::RoomInfo* out);

void GRPC_TO_TURBOLINK(const ::lobby::CreateRoomRequest* in, FGrpcLobbyCreateRoomRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyCreateRoomRequest* in, ::lobby::CreateRoomRequest* out);

void GRPC_TO_TURBOLINK(const ::lobby::JoinRoomRequest* in, FGrpcLobbyJoinRoomRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyJoinRoomRequest* in, ::lobby::JoinRoomRequest* out);

void GRPC_TO_TURBOLINK(const ::lobby::GetRoomListRequest* in, FGrpcLobbyGetRoomListRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyGetRoomListRequest* in, ::lobby::GetRoomListRequest* out);

void GRPC_TO_TURBOLINK(const ::lobby::GetRoomListResponse* in, FGrpcLobbyGetRoomListResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyGetRoomListResponse* in, ::lobby::GetRoomListResponse* out);

void GRPC_TO_TURBOLINK(const ::lobby::UpdateRoomInfoRequest* in, FGrpcLobbyUpdateRoomInfoRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyUpdateRoomInfoRequest* in, ::lobby::UpdateRoomInfoRequest* out);

void GRPC_TO_TURBOLINK(const ::lobby::UpdateRoomInfoResponse* in, FGrpcLobbyUpdateRoomInfoResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyUpdateRoomInfoResponse* in, ::lobby::UpdateRoomInfoResponse* out);

void GRPC_TO_TURBOLINK(const ::lobby::ConnectionInfo* in, FGrpcLobbyConnectionInfo* out);
void TURBOLINK_TO_GRPC(const FGrpcLobbyConnectionInfo* in, ::lobby::ConnectionInfo* out);

typedef grpc::ClientAsyncResponseReader<::lobby::ConnectionInfo> LobbyService_CreateRoom_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::lobby::ConnectionInfo> LobbyService_JoinRoom_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::lobby::GetRoomListResponse> LobbyService_GetRoomList_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::lobby::UpdateRoomInfoResponse> LobbyService_UpdateRoomInfo_ReaderWriter;
