//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SLobby/LobbyMessage.h"
#include "SLobby/LobbyMarshaling.h"
class GrpcContext_LobbyService_CreateRoom : public GrpcContext_Ping_Pong<LobbyService_CreateRoom_ReaderWriter, ::lobby::ConnectionInfo>
{
	friend class ULobbyServiceClient;
	typedef GrpcContext_Ping_Pong<LobbyService_CreateRoom_ReaderWriter, ::lobby::ConnectionInfo> Super;

private:
	void Call(const FGrpcLobbyCreateRoomRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_LobbyService_CreateRoom(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_LobbyService_JoinRoom : public GrpcContext_Ping_Pong<LobbyService_JoinRoom_ReaderWriter, ::lobby::ConnectionInfo>
{
	friend class ULobbyServiceClient;
	typedef GrpcContext_Ping_Pong<LobbyService_JoinRoom_ReaderWriter, ::lobby::ConnectionInfo> Super;

private:
	void Call(const FGrpcLobbyJoinRoomRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_LobbyService_JoinRoom(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_LobbyService_GetRoomList : public GrpcContext_Ping_Pong<LobbyService_GetRoomList_ReaderWriter, ::lobby::GetRoomListResponse>
{
	friend class ULobbyServiceClient;
	typedef GrpcContext_Ping_Pong<LobbyService_GetRoomList_ReaderWriter, ::lobby::GetRoomListResponse> Super;

private:
	void Call(const FGrpcLobbyGetRoomListRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_LobbyService_GetRoomList(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

class GrpcContext_LobbyService_UpdateRoomInfo : public GrpcContext_Ping_Pong<LobbyService_UpdateRoomInfo_ReaderWriter, ::lobby::UpdateRoomInfoResponse>
{
	friend class ULobbyServiceClient;
	typedef GrpcContext_Ping_Pong<LobbyService_UpdateRoomInfo_ReaderWriter, ::lobby::UpdateRoomInfoResponse> Super;

private:
	void Call(const FGrpcLobbyUpdateRoomInfoRequest& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_LobbyService_UpdateRoomInfo(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

