//Generated by TurboLink CodeGenerator, do not edit!
#include "SLobby/LobbyClient.h"
#include "SLobby/LobbyService.h"
#include "LobbyContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle ULobbyServiceClient::InitCreateRoom()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_CreateRoom>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::CreateRoom(FGrpcContextHandle Handle, const FGrpcLobbyCreateRoomRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextCreateRoom = StaticCastSharedPtr<GrpcContext_LobbyService_CreateRoom>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextCreateRoom->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextCreateRoom->RpcContext->set_deadline(deadLine);
		}
		contextCreateRoom->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitJoinRoom()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_JoinRoom>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::JoinRoom(FGrpcContextHandle Handle, const FGrpcLobbyJoinRoomRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextJoinRoom = StaticCastSharedPtr<GrpcContext_LobbyService_JoinRoom>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextJoinRoom->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextJoinRoom->RpcContext->set_deadline(deadLine);
		}
		contextJoinRoom->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitGetRoomList()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_GetRoomList>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::GetRoomList(FGrpcContextHandle Handle, const FGrpcLobbyGetRoomListRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextGetRoomList = StaticCastSharedPtr<GrpcContext_LobbyService_GetRoomList>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextGetRoomList->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextGetRoomList->RpcContext->set_deadline(deadLine);
		}
		contextGetRoomList->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitUpdateRoomState()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_UpdateRoomState>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::UpdateRoomState(FGrpcContextHandle Handle, const FGrpcLobbyUpdateRoomStateRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextUpdateRoomState = StaticCastSharedPtr<GrpcContext_LobbyService_UpdateRoomState>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextUpdateRoomState->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextUpdateRoomState->RpcContext->set_deadline(deadLine);
		}
		contextUpdateRoomState->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitUpdateRoomConfig()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_UpdateRoomConfig>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::UpdateRoomConfig(FGrpcContextHandle Handle, const FGrpcLobbyUpdateRoomConfigRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextUpdateRoomConfig = StaticCastSharedPtr<GrpcContext_LobbyService_UpdateRoomConfig>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextUpdateRoomConfig->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextUpdateRoomConfig->RpcContext->set_deadline(deadLine);
		}
		contextUpdateRoomConfig->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitChangeRoomPassword()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_ChangeRoomPassword>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::ChangeRoomPassword(FGrpcContextHandle Handle, const FGrpcLobbyChangeRoomPasswordRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextChangeRoomPassword = StaticCastSharedPtr<GrpcContext_LobbyService_ChangeRoomPassword>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextChangeRoomPassword->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextChangeRoomPassword->RpcContext->set_deadline(deadLine);
		}
		contextChangeRoomPassword->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitChangeRoomOwner()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_ChangeRoomOwner>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::ChangeRoomOwner(FGrpcContextHandle Handle, const FGrpcLobbyChangeRoomOwnerRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextChangeRoomOwner = StaticCastSharedPtr<GrpcContext_LobbyService_ChangeRoomOwner>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextChangeRoomOwner->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextChangeRoomOwner->RpcContext->set_deadline(deadLine);
		}
		contextChangeRoomOwner->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitDeleteRoom()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_DeleteRoom>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::DeleteRoom(FGrpcContextHandle Handle, const FGrpcLobbyDeleteRoomRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextDeleteRoom = StaticCastSharedPtr<GrpcContext_LobbyService_DeleteRoom>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextDeleteRoom->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextDeleteRoom->RpcContext->set_deadline(deadLine);
		}
		contextDeleteRoom->Call(Request);
	}
}

FGrpcContextHandle ULobbyServiceClient::InitListenRoomUpdates()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_LobbyService_ListenRoomUpdates>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void ULobbyServiceClient::ListenRoomUpdates(FGrpcContextHandle Handle, const FGrpcLobbyListenRoomUpdatesRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextListenRoomUpdates = StaticCastSharedPtr<GrpcContext_LobbyService_ListenRoomUpdates>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextListenRoomUpdates->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextListenRoomUpdates->RpcContext->set_deadline(deadLine);
		}
		contextListenRoomUpdates->Call(Request);
	}
}

void ULobbyServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void ULobbyServiceClient::Shutdown()
{
	OnCreateRoomResponse.Clear();
	OnJoinRoomResponse.Clear();
	OnGetRoomListResponse.Clear();
	OnUpdateRoomStateResponse.Clear();
	OnUpdateRoomConfigResponse.Clear();
	OnChangeRoomPasswordResponse.Clear();
	OnChangeRoomOwnerResponse.Clear();
	OnDeleteRoomResponse.Clear();
	OnListenRoomUpdatesResponse.Clear();
	Super::Shutdown();
}

