//Generated by TurboLink CodeGenerator, do not edit!
#include "LobbyService_Private.h"

void ULobbyServiceCreateRoomLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcLobbyConnectionInfo& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnCreateRoomResponse.RemoveDynamic(this, &ULobbyServiceCreateRoomLambdaWrapper::OnResponse);
}

void ULobbyServiceJoinRoomLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcLobbyConnectionInfo& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnJoinRoomResponse.RemoveDynamic(this, &ULobbyServiceJoinRoomLambdaWrapper::OnResponse);
}

void ULobbyServiceGetRoomListLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcLobbyGetRoomListResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGetRoomListResponse.RemoveDynamic(this, &ULobbyServiceGetRoomListLambdaWrapper::OnResponse);
}

void ULobbyServiceUpdateRoomInfoLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcLobbyUpdateRoomInfoResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnUpdateRoomInfoResponse.RemoveDynamic(this, &ULobbyServiceUpdateRoomInfoLambdaWrapper::OnResponse);
}

