//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SLobby/LobbyClient.h"
#include "LobbyService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API ULobbyService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	ULobbyServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	ULobbyServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyCreateRoomResponse& Response)> FCreateRoomResponseLambda;
	void CallCreateRoom(const FGrpcLobbyCreateRoomRequest& Request, FCreateRoomResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyJoinRoomResponse& Response)> FJoinRoomResponseLambda;
	void CallJoinRoom(const FGrpcLobbyJoinRoomRequest& Request, FJoinRoomResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyGetRoomListResponse& Response)> FGetRoomListResponseLambda;
	void CallGetRoomList(const FGrpcLobbyGetRoomListRequest& Request, FGetRoomListResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyUpdateRoomStateResponse& Response)> FUpdateRoomStateResponseLambda;
	void CallUpdateRoomState(const FGrpcLobbyUpdateRoomStateRequest& Request, FUpdateRoomStateResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyUpdateRoomConfigResponse& Response)> FUpdateRoomConfigResponseLambda;
	void CallUpdateRoomConfig(const FGrpcLobbyUpdateRoomConfigRequest& Request, FUpdateRoomConfigResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyUpdatePlayerStateResponse& Response)> FUpdatePlayerStateResponseLambda;
	void CallUpdatePlayerState(const FGrpcLobbyUpdatePlayerStateRequest& Request, FUpdatePlayerStateResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyChangeRoomPasswordResponse& Response)> FChangeRoomPasswordResponseLambda;
	void CallChangeRoomPassword(const FGrpcLobbyChangeRoomPasswordRequest& Request, FChangeRoomPasswordResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyChangeRoomOwnerResponse& Response)> FChangeRoomOwnerResponseLambda;
	void CallChangeRoomOwner(const FGrpcLobbyChangeRoomOwnerRequest& Request, FChangeRoomOwnerResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyDeleteRoomResponse& Response)> FDeleteRoomResponseLambda;
	void CallDeleteRoom(const FGrpcLobbyDeleteRoomRequest& Request, FDeleteRoomResponseLambda ResponseLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyListenRoomConfigUpdatesResponse& Response)> FUpdateRoomConfigStreamResponseLambda;
	typedef TFunction<void()> FUpdateRoomConfigStreamFinishLambda;
	void CallUpdateRoomConfigStream(const FGrpcLobbyListenRoomConfigUpdatesRequest& Request, FUpdateRoomConfigStreamResponseLambda ResponseLambda, FUpdateRoomConfigStreamFinishLambda FinishLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcLobbyListenPlayerListUpdatesResponse& Response)> FUpdatePlayerListStreamResponseLambda;
	typedef TFunction<void()> FUpdatePlayerListStreamFinishLambda;
	void CallUpdatePlayerListStream(const FGrpcLobbyListenPlayerListUpdatesRequest& Request, FUpdatePlayerListStreamResponseLambda ResponseLambda, FUpdatePlayerListStreamFinishLambda FinishLambda, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	class Private;
	Private* const d = nullptr;

public:
	ULobbyService();
	virtual ~ULobbyService();
};

