//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleProtobuf/TimestampMessage.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "LobbyMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Lobby.RoomState", ScriptName="EGrpcLobbyRoomState"))
enum class EGrpcLobbyRoomState : uint8
{
    ROOM_STATE_UNSPECIFIED=0,
    ROOM_STATE_CREATING=1,
    ROOM_STATE_WAITING=2,
    ROOM_STATE_PLAYING=3,
    ROOM_STATE_CLOSED=4,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.RoomVisibility", ScriptName="EGrpcLobbyRoomVisibility"))
enum class EGrpcLobbyRoomVisibility : uint8
{
    ROOM_VISIBILITY_UNSPECIFIED=0,
    ROOM_VISIBILITY_PUBLIC=1,
    ROOM_VISIBILITY_PRIVATE=2,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.GameMode", ScriptName="EGrpcLobbyGameMode"))
enum class EGrpcLobbyGameMode : uint8
{
    GAME_MODE_UNSPECIFIED=0,
    GAME_MODE_DEFAULT=1,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.GameMap", ScriptName="EGrpcLobbyGameMap"))
enum class EGrpcLobbyGameMap : uint8
{
    GAME_MAP_UNSPECIFIED=0,
    GAME_MAP_DEFAULT=1,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.PlayerState", ScriptName="EGrpcLobbyPlayerState"))
enum class EGrpcLobbyPlayerState : uint8
{
    PLAYER_STATE_UNSPECIFIED=0,
    PLAYER_STATE_JOINING=1,
    PLAYER_STATE_JOINED=2,
    PLAYER_STATE_LEAVE=3,
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.RoomPreview",
    HasNativeMake = "TurboLinkGrpc.GrpcLobbyRoomPreviewHelperLibrary.MakeRoomPreview",
    HasNativeBreak = "TurboLinkGrpc.GrpcLobbyRoomPreviewHelperLibrary.BreakRoomPreview"))
struct FGrpcLobbyRoomPreview : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    TSharedPtr<FGrpcLobbyRoomConfig> Config;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 CurrentPlayers = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.CreateRoomRequest",
    HasNativeMake = "TurboLinkGrpc.GrpcLobbyCreateRoomRequestHelperLibrary.MakeCreateRoomRequest",
    HasNativeBreak = "TurboLinkGrpc.GrpcLobbyCreateRoomRequestHelperLibrary.BreakCreateRoomRequest"))
struct FGrpcLobbyCreateRoomRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    TSharedPtr<FGrpcLobbyRoomConfig> Config;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.CreateRoomResponse",
    HasNativeMake = "TurboLinkGrpc.GrpcLobbyCreateRoomResponseHelperLibrary.MakeCreateRoomResponse",
    HasNativeBreak = "TurboLinkGrpc.GrpcLobbyCreateRoomResponseHelperLibrary.BreakCreateRoomResponse"))
struct FGrpcLobbyCreateRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    TSharedPtr<FGrpcLobbyRoomConnectionInfo> Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.JoinRoomRequest"))
struct FGrpcLobbyJoinRoomRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.JoinRoomResponse",
    HasNativeMake = "TurboLinkGrpc.GrpcLobbyJoinRoomResponseHelperLibrary.MakeJoinRoomResponse",
    HasNativeBreak = "TurboLinkGrpc.GrpcLobbyJoinRoomResponseHelperLibrary.BreakJoinRoomResponse"))
struct FGrpcLobbyJoinRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    TSharedPtr<FGrpcLobbyRoomConnectionInfo> Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.GetRoomListRequest"))
struct FGrpcLobbyGetRoomListRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomVisibility Visibility = static_cast<EGrpcLobbyRoomVisibility>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMode Mode = static_cast<EGrpcLobbyGameMode>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMap Map = static_cast<EGrpcLobbyGameMap>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.GetRoomListResponse"))
struct FGrpcLobbyGetRoomListResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcLobbyRoomPreview> Rooms;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.RoomConnectionInfo"))
struct FGrpcLobbyRoomConnectionInfo : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Host = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 Port = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.RoomPlayer"))
struct FGrpcLobbyRoomPlayer : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyPlayerState State = static_cast<EGrpcLobbyPlayerState>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool IsOwner = false;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcGoogleProtobufTimestamp JoinedAt;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.Room",
    HasNativeMake = "TurboLinkGrpc.GrpcLobbyRoomHelperLibrary.MakeRoom",
    HasNativeBreak = "TurboLinkGrpc.GrpcLobbyRoomHelperLibrary.BreakRoom"))
struct FGrpcLobbyRoom : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString PasswordEncrypted = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomState State = static_cast<EGrpcLobbyRoomState>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString OwnerId = "";

    TSharedPtr<FGrpcLobbyRoomConfig> Config;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcLobbyRoomPlayer> Players;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 PlayerCount = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConnectionInfo Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.RoomConfig"))
struct FGrpcLobbyRoomConfig : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomVisibility Visibility = static_cast<EGrpcLobbyRoomVisibility>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMode Mode = static_cast<EGrpcLobbyGameMode>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMap Map = static_cast<EGrpcLobbyGameMap>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 MaxPlayers = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomStateRequest"))
struct FGrpcLobbyUpdateRoomStateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomState State = static_cast<EGrpcLobbyRoomState>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomStateResponse"))
struct FGrpcLobbyUpdateRoomStateResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomState UpdatedState = static_cast<EGrpcLobbyRoomState>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomConfigRequest"))
struct FGrpcLobbyUpdateRoomConfigRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig Config;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomConfigResponse"))
struct FGrpcLobbyUpdateRoomConfigResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig UpdatedConfig;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdatePlayerStateRequest"))
struct FGrpcLobbyUpdatePlayerStateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyPlayerState State = static_cast<EGrpcLobbyPlayerState>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdatePlayerStateResponse"))
struct FGrpcLobbyUpdatePlayerStateResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyPlayerState UpdatedState = static_cast<EGrpcLobbyPlayerState>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomPasswordRequest"))
struct FGrpcLobbyChangeRoomPasswordRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomPasswordResponse"))
struct FGrpcLobbyChangeRoomPasswordResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomOwnerRequest"))
struct FGrpcLobbyChangeRoomOwnerRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString UserId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomOwnerResponse"))
struct FGrpcLobbyChangeRoomOwnerResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString OwnerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.DeleteRoomRequest"))
struct FGrpcLobbyDeleteRoomRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.DeleteRoomResponse"))
struct FGrpcLobbyDeleteRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ListenRoomConfigUpdatesRequest"))
struct FGrpcLobbyListenRoomConfigUpdatesRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ListenRoomConfigUpdatesResponse"))
struct FGrpcLobbyListenRoomConfigUpdatesResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig UpdatedConfig;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ListenPlayerListUpdatesRequest"))
struct FGrpcLobbyListenPlayerListUpdatesRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ListenPlayerListUpdatesResponse"))
struct FGrpcLobbyListenPlayerListUpdatesResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcLobbyRoomPlayer> Players;
};

UCLASS()
class UGrpcLobbyRoomPreviewHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static FGrpcLobbyRoomPreview MakeRoomPreview( 
        FString RoomId, FGrpcLobbyRoomConfig Config, int32 CurrentPlayers 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static void BreakRoomPreview(const FGrpcLobbyRoomPreview& RoomPreview,  
        FString& RoomId, FGrpcLobbyRoomConfig& Config, int32& CurrentPlayers 
    );
};

UCLASS()
class UGrpcLobbyCreateRoomRequestHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static FGrpcLobbyCreateRoomRequest MakeCreateRoomRequest( 
        FGrpcLobbyRoomConfig Config, FString Password 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static void BreakCreateRoomRequest(const FGrpcLobbyCreateRoomRequest& CreateRoomRequest,  
        FGrpcLobbyRoomConfig& Config, FString& Password 
    );
};

UCLASS()
class UGrpcLobbyCreateRoomResponseHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static FGrpcLobbyCreateRoomResponse MakeCreateRoomResponse( 
        FGrpcLobbyRoomConnectionInfo Connection 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static void BreakCreateRoomResponse(const FGrpcLobbyCreateRoomResponse& CreateRoomResponse,  
        FGrpcLobbyRoomConnectionInfo& Connection 
    );
};

UCLASS()
class UGrpcLobbyJoinRoomResponseHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static FGrpcLobbyJoinRoomResponse MakeJoinRoomResponse( 
        FGrpcLobbyRoomConnectionInfo Connection 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static void BreakJoinRoomResponse(const FGrpcLobbyJoinRoomResponse& JoinRoomResponse,  
        FGrpcLobbyRoomConnectionInfo& Connection 
    );
};

UCLASS()
class UGrpcLobbyRoomHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static FGrpcLobbyRoom MakeRoom( 
        FString RoomId, FString PasswordEncrypted, EGrpcLobbyRoomState State, 
        FString OwnerId, FGrpcLobbyRoomConfig Config, TArray<FGrpcLobbyRoomPlayer> Players, 
        int32 PlayerCount, FGrpcLobbyRoomConnectionInfo Connection 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Lobby", meta=(BlueprintThreadSafe))
    static void BreakRoom(const FGrpcLobbyRoom& Room,  
        FString& RoomId, FString& PasswordEncrypted, EGrpcLobbyRoomState& State, 
        FString& OwnerId, FGrpcLobbyRoomConfig& Config, TArray<FGrpcLobbyRoomPlayer>& Players, 
        int32& PlayerCount, FGrpcLobbyRoomConnectionInfo& Connection 
    );
};
