//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "LobbyMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Lobby.RoomState", ScriptName="EGrpcLobbyRoomState"))
enum class EGrpcLobbyRoomState : uint8
{
    ROOM_STATE_UNSPECIFIED=0,
    ROOM_STATE_OPEN=1,
    ROOM_STATE_PLAYING=2,
    ROOM_STATE_CLOSED=3,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.RoomVisibility", ScriptName="EGrpcLobbyRoomVisibility"))
enum class EGrpcLobbyRoomVisibility : uint8
{
    ROOM_VISIBILITY_UNSPECIFIED=0,
    ROOM_VISIBILITY_PUBLIC=1,
    ROOM_VISIBILITY_PRIVATE=2,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.GameMode", ScriptName="EGrpcLobbyGameMode"))
enum class EGrpcLobbyGameMode : uint8
{
    GAME_MODE_UNSPECIFIED=0,
    GAME_MODE_DEFAULT=1,
};

UENUM(BlueprintType, meta = (DisplayName="Lobby.GameMap", ScriptName="EGrpcLobbyGameMap"))
enum class EGrpcLobbyGameMap : uint8
{
    GAME_MAP_UNSPECIFIED=0,
    GAME_MAP_DEFAULT=1,
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.RoomConnectionInfo"))
struct FGrpcLobbyRoomConnectionInfo : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Host = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 Port = 0;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.RoomConfig"))
struct FGrpcLobbyRoomConfig : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomVisibility Visibility = static_cast<EGrpcLobbyRoomVisibility>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMode Mode = static_cast<EGrpcLobbyGameMode>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMap Map = static_cast<EGrpcLobbyGameMap>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.Room"))
struct FGrpcLobbyRoom : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomCode = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString OwnerId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig Config;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomState State = static_cast<EGrpcLobbyRoomState>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 MaxPlayers = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 CurrentPlayers = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConnectionInfo Connection;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString GameVersion = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.CreateRoomRequest"))
struct FGrpcLobbyCreateRoomRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString GameVersion = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomName = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig Config;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.CreateRoomResponse"))
struct FGrpcLobbyCreateRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConnectionInfo Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.QuickMatchRequest"))
struct FGrpcLobbyQuickMatchRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString GameVersion = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.QuickMatchResponse"))
struct FGrpcLobbyQuickMatchResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConnectionInfo Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.JoinRoomRequest"))
struct FGrpcLobbyJoinRoomRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString GameVersion = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.JoinRoomResponse"))
struct FGrpcLobbyJoinRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConnectionInfo Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.JoinRoomWithCodeRequest"))
struct FGrpcLobbyJoinRoomWithCodeRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString GameVersion = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomCode = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.JoinRoomWithCodeResponse"))
struct FGrpcLobbyJoinRoomWithCodeResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConnectionInfo Connection;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.GetRoomListRequest"))
struct FGrpcLobbyGetRoomListRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString GameVersion = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomVisibility Visibility = static_cast<EGrpcLobbyRoomVisibility>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMode Mode = static_cast<EGrpcLobbyGameMode>(0);

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyGameMap Map = static_cast<EGrpcLobbyGameMap>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.GetRoomListResponse"))
struct FGrpcLobbyGetRoomListResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    TArray<FGrpcLobbyRoom> Rooms;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomStateRequest"))
struct FGrpcLobbyUpdateRoomStateRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomState State = static_cast<EGrpcLobbyRoomState>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomStateResponse"))
struct FGrpcLobbyUpdateRoomStateResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    EGrpcLobbyRoomState UpdatedState = static_cast<EGrpcLobbyRoomState>(0);
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomConfigRequest"))
struct FGrpcLobbyUpdateRoomConfigRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig Config;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.UpdateRoomConfigResponse"))
struct FGrpcLobbyUpdateRoomConfigResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FGrpcLobbyRoomConfig UpdatedConfig;
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomPasswordRequest"))
struct FGrpcLobbyChangeRoomPasswordRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Password = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomPasswordResponse"))
struct FGrpcLobbyChangeRoomPasswordResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString RoomId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomOwnerRequest"))
struct FGrpcLobbyChangeRoomOwnerRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString NewOwnerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ChangeRoomOwnerResponse"))
struct FGrpcLobbyChangeRoomOwnerResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString OwnerId = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.DeleteRoomRequest"))
struct FGrpcLobbyDeleteRoomRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.DeleteRoomResponse"))
struct FGrpcLobbyDeleteRoomResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Lobby.ListenRoomUpdatesRequest"))
struct FGrpcLobbyListenRoomUpdatesRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};
