//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SLobby/LobbyMessage.h"
#include "LobbyClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnLobbyServiceCreateRoomResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcLobbyConnectionInfo&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnLobbyServiceJoinRoomResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcLobbyConnectionInfo&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnLobbyServiceGetRoomListResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcLobbyGetRoomListResponse&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnLobbyServiceUpdateRoomInfoResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcLobbyUpdateRoomInfoResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API ULobbyServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnLobbyServiceCreateRoomResponse OnCreateRoomResponse;

	UPROPERTY(BlueprintAssignable)
	FOnLobbyServiceJoinRoomResponse OnJoinRoomResponse;

	UPROPERTY(BlueprintAssignable)
	FOnLobbyServiceGetRoomListResponse OnGetRoomListResponse;

	UPROPERTY(BlueprintAssignable)
	FOnLobbyServiceUpdateRoomInfoResponse OnUpdateRoomInfoResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitCreateRoom();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void CreateRoom(FGrpcContextHandle Handle, const FGrpcLobbyCreateRoomRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitJoinRoom();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void JoinRoom(FGrpcContextHandle Handle, const FGrpcLobbyJoinRoomRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitGetRoomList();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void GetRoomList(FGrpcContextHandle Handle, const FGrpcLobbyGetRoomListRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitUpdateRoomInfo();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void UpdateRoomInfo(FGrpcContextHandle Handle, const FGrpcLobbyUpdateRoomInfoRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

