// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game.proto

#include "game.pb.h"
#include "game.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace game {

static const char* GameService_method_names[] = {
  "/game.GameService/GetServiceVersion",
};

std::unique_ptr< GameService::Stub> GameService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GameService::Stub> stub(new GameService::Stub(channel, options));
  return stub;
}

GameService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetServiceVersion_(GameService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GameService::Stub::GetServiceVersion(::grpc::ClientContext* context, const ::game::GetServiceVersionRequest& request, ::game::GetServiceVersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::game::GetServiceVersionRequest, ::game::GetServiceVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetServiceVersion_, context, request, response);
}

void GameService::Stub::async::GetServiceVersion(::grpc::ClientContext* context, const ::game::GetServiceVersionRequest* request, ::game::GetServiceVersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::game::GetServiceVersionRequest, ::game::GetServiceVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetServiceVersion_, context, request, response, std::move(f));
}

void GameService::Stub::async::GetServiceVersion(::grpc::ClientContext* context, const ::game::GetServiceVersionRequest* request, ::game::GetServiceVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetServiceVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::game::GetServiceVersionResponse>* GameService::Stub::PrepareAsyncGetServiceVersionRaw(::grpc::ClientContext* context, const ::game::GetServiceVersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::game::GetServiceVersionResponse, ::game::GetServiceVersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetServiceVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::game::GetServiceVersionResponse>* GameService::Stub::AsyncGetServiceVersionRaw(::grpc::ClientContext* context, const ::game::GetServiceVersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetServiceVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

GameService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GameService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GameService::Service, ::game::GetServiceVersionRequest, ::game::GetServiceVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GameService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::game::GetServiceVersionRequest* req,
             ::game::GetServiceVersionResponse* resp) {
               return service->GetServiceVersion(ctx, req, resp);
             }, this)));
}

GameService::Service::~Service() {
}

::grpc::Status GameService::Service::GetServiceVersion(::grpc::ServerContext* context, const ::game::GetServiceVersionRequest* request, ::game::GetServiceVersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace game

