//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "TimestampMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="GoogleProtobuf.Timestamp"))
struct FGrpcGoogleProtobufTimestamp : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int64 Seconds = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    int32 Nanos = 0;
};
