//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SGreet/GreetMessage.h"
#include "GreetClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnGreeterServiceSayHelloResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGreetHelloResponse&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UGreeterServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnGreeterServiceSayHelloResponse OnSayHelloResponse;

public:
	UFUNCTION(BlueprintCallable, Category = TurboLink)
	FGrpcContextHandle InitSayHello();

	UFUNCTION(BlueprintCallable, Category = TurboLink, meta = (AdvancedDisplay = 2))
	void SayHello(FGrpcContextHandle Handle, const FGrpcGreetHelloRequest& Request, FGrpcMetaData MetaData = FGrpcMetaData(), float DeadLineSeconds = 0.f);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable, Category = TurboLink)
	void TryCancel(FGrpcContextHandle Handle);
};

