//Generated by TurboLink CodeGenerator, do not edit!
#include "AuthService_Private.h"

void UAuthServiceGuestLoginLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcAuthResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnGuestLoginResponse.RemoveDynamic(this, &UAuthServiceGuestLoginLambdaWrapper::OnResponse);
}

void UAuthServiceRegisterGameServerLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcAuthResponse& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnRegisterGameServerResponse.RemoveDynamic(this, &UAuthServiceRegisterGameServerLambdaWrapper::OnResponse);
}

