//Generated by TurboLink CodeGenerator, do not edit!
#include "AuthMarshaling.h"

void GRPC_TO_TURBOLINK(const ::auth::GuestLoginRequest* in, FGrpcAuthGuestLoginRequest* out)
{
    out->UserName=StringCast<TCHAR>((const UTF8CHAR*)(in->user_name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcAuthGuestLoginRequest* in, ::auth::GuestLoginRequest* out)
{
    out->set_user_name((const char*)StringCast<UTF8CHAR>(*(in->UserName)).Get());
}

void GRPC_TO_TURBOLINK(const ::auth::RegisterGameServerRequest* in, FGrpcAuthRegisterGameServerRequest* out)
{
    out->ServerName=StringCast<TCHAR>((const UTF8CHAR*)(in->server_name().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcAuthRegisterGameServerRequest* in, ::auth::RegisterGameServerRequest* out)
{
    out->set_server_name((const char*)StringCast<UTF8CHAR>(*(in->ServerName)).Get());
}

void GRPC_TO_TURBOLINK(const ::auth::Response* in, FGrpcAuthResponse* out)
{
    out->Token=StringCast<TCHAR>((const UTF8CHAR*)(in->token().c_str())).Get();
}

void TURBOLINK_TO_GRPC(const FGrpcAuthResponse* in, ::auth::Response* out)
{
    out->set_token((const char*)StringCast<UTF8CHAR>(*(in->Token)).Get());
}

