//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SAuth/AuthMessage.h"
#include "TurboLinkGrpcContext.h"
#include "auth.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::auth::GuestLoginRequest* in, FGrpcAuthGuestLoginRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcAuthGuestLoginRequest* in, ::auth::GuestLoginRequest* out);

void GRPC_TO_TURBOLINK(const ::auth::RegisterGameServerRequest* in, FGrpcAuthRegisterGameServerRequest* out);
void TURBOLINK_TO_GRPC(const FGrpcAuthRegisterGameServerRequest* in, ::auth::RegisterGameServerRequest* out);

void GRPC_TO_TURBOLINK(const ::auth::Response* in, FGrpcAuthResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcAuthResponse* in, ::auth::Response* out);

typedef grpc::ClientAsyncResponseReader<::auth::Response> AuthService_GuestLogin_ReaderWriter;
typedef grpc::ClientAsyncResponseReader<::auth::Response> AuthService_RegisterGameServer_ReaderWriter;
