//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SAuth/AuthService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "auth.grpc.pb.h"
#include "AuthService_Private.generated.h"

class UAuthService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::auth::AuthService::Stub> Stub;
};


UCLASS()
class UAuthServiceGuestLoginLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UAuthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcAuthLoginResponse& Response);
public:
	FGrpcContextHandle Handle;
	UAuthService::FGuestLoginResponseLambda ResponseLambda;
};

UCLASS()
class UAuthServiceValidateUserTokenLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UAuthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcAuthValidateUserTokenResponse& Response);
public:
	FGrpcContextHandle Handle;
	UAuthService::FValidateUserTokenResponseLambda ResponseLambda;
};

