//Generated by TurboLink CodeGenerator, do not edit!
#include "SAuth/AuthClient.h"
#include "SAuth/AuthService.h"
#include "AuthContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UAuthServiceClient::InitGuestLogin()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_AuthService_GuestLogin>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UAuthServiceClient::GuestLogin(FGrpcContextHandle Handle, const FGrpcAuthGuestLoginRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextGuestLogin = StaticCastSharedPtr<GrpcContext_AuthService_GuestLogin>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextGuestLogin->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextGuestLogin->RpcContext->set_deadline(deadLine);
		}
		contextGuestLogin->Call(Request);
	}
}

FGrpcContextHandle UAuthServiceClient::InitValidateUserToken()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_AuthService_ValidateUserToken>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UAuthServiceClient::ValidateUserToken(FGrpcContextHandle Handle, const FGrpcAuthValidateUserTokenRequest& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextValidateUserToken = StaticCastSharedPtr<GrpcContext_AuthService_ValidateUserToken>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextValidateUserToken->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextValidateUserToken->RpcContext->set_deadline(deadLine);
		}
		contextValidateUserToken->Call(Request);
	}
}

void UAuthServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UAuthServiceClient::Shutdown()
{
	OnGuestLoginResponse.Clear();
	OnValidateUserTokenResponse.Clear();
	Super::Shutdown();
}

