//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "GameMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Game.GetServiceVersionRequest"))
struct FGrpcGameGetServiceVersionRequest : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()
};

USTRUCT(BlueprintType, meta = (DisplayName="Game.GetServiceVersionResponse"))
struct FGrpcGameGetServiceVersionResponse : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString Version = "";
};
